// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package tutorial

import (
	"database/sql"
)

type Comment struct {
	CommentID  int32
	PostID     sql.NullInt32
	Content    sql.NullString
	TimePosted sql.NullTime
	ID         sql.NullInt32
	Username   sql.NullString
	Points     sql.NullInt32
}

type CommentLike struct {
	UserID sql.NullString
	PostID sql.NullString
}

type Post struct {
	PostID     int32
	Title      sql.NullString
	Content    sql.NullString
	TimePosted sql.NullTime
	ID         sql.NullInt32
	Category   sql.NullString
}

type User struct {
	ID          int32
	Username    sql.NullString
	PasswordKey sql.NullString
	Email       sql.NullString
	FullName    sql.NullString
}
